### ISSUE TITLE
how to set the shared folders on the indexer?

### ISSUE THREAD

**Issue by Rigolino1** [xieqifei/onedrive_vercel_share#2]
i mean how to set movies shared folder for index on the page? how to add

**Comment by xieqifei** [comment]
Make sure you have set base directory on the file _config/site.config.ja_ baseDirectory: '/public_share'.The public_share should in the root. Then creat a new file in public_share,name it  **.password**. Add your password in this file, so that your directory is protected. If you don't want protect the directory, just clear the list of protected path in _config/site.config.js_.

**Comment by Rigolino1** [comment]
yes bro, but i need to add shared folders to my indexer, i mean, Max shared to me a folder with movies, and i put the direct access to this folder of Max on my public folder, but the indexer not read de direct access to this folder

**Comment by xieqifei** [comment]
Unfortunately, this functionality is not available. But as I know, there is a repository named Alist, that support it. With it you can index other's alist in your alist.
